; PlatformIO Project Configuration File

[platformio]
default_envs = esplolin_c3_mini32dev
;default_envs = esp32-s3-devkitc-1
;default_envs = esp32dev


; ===============================
; ESP32 C3 MINI
; ===============================
[env:esplolin_c3_mini32dev]
platform = espressif32@6.3.2
board = lolin_c3_mini
framework = arduino
monitor_speed = 115200

board_build.partitions = no_ota.csv

build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

lib_deps =
    h2zero/NimBLE-Arduino@^1.4.0
    miguelbalboa/MFRC522@^1.4.10


; ===============================
; ESP32 S3
; ===============================
[env:esp32-s3-devkitc-1]
platform = espressif32@6.3.2
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MSC_ON_BOOT=0
    -DARDUINO_USB_DFU_ON_BOOT=0

lib_deps =
    h2zero/NimBLE-Arduino@^1.4.0
    miguelbalboa/MFRC522@^1.4.10


; ===============================
; ESP32 CLÁSSICO
; ===============================
[env:esp32dev]
platform = espressif32@6.3.2
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    h2zero/NimBLE-Arduino@^1.4.0
    miguelbalboa/MFRC522@^1.4.10